# Generated by Django 4.2.29 on 2026-03-24 21:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('expired_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'token_blacklist',
            },
        ),
    ]
